---
apiVersion: v1
kind: Pod
metadata:
  name: tasks-conversion-webhook
  labels:
    app.kubernetes.io/name: tasks-conversion-webhook
spec:
  containers:
  - name: tasks-conversion-webhook
    image: akutz/pucr
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: tasks-conversion-webhook
      mountPath: "/pucr/tls"
      readOnly: true
    ports:
    - containerPort: 9443
      name: https
    command:
    - /pucr/server
    args:
    - -tls-cert-file
    - /pucr/tls/server.crt
    - -tls-private-key-file
    - /pucr/tls/server.key
  volumes:
  - name: tasks-conversion-webhook
    secret:
      secretName: tasks-conversion-webhook
      items:
      - key: crt
        path: server.crt
      - key: key
        path: server.key
---
apiVersion: v1
kind: Secret
metadata:
  name: tasks-conversion-webhook
data:
  crt: Cg==
  key: Cg==
---
apiVersion: v1
kind: Service
metadata:
  name: tasks-conversion-webhook
spec:
  selector:
    app.kubernetes.io/name: tasks-conversion-webhook
  ports:
  - protocol: TCP
    port: 9443
    targetPort: 9443
