---
apiVersion: v1
kind: Pod
metadata:
  name: tasks-conversion-webhook-server
  labels:
    app.kubernetes.io/name: tasks-conversion-webhook-server
spec:
  containers:
  - name: tasks-conversion-webhook-server
    image: tasks-conversion-webhook-server
    imagePullPolicy: Never
    volumeMounts:
    - name: tasks-conversion-webhook-server
      mountPath: "/webserver/tls/"
      readOnly: true
    ports:
    - containerPort: 9443
      name: https
    command:
    - /webserver/conversion-webhook-server
    args:
    - -tls-cert-file
    - /webserver/tls/server.crt
    - -tls-private-key-file
    - /webserver/tls/server.key
  volumes:
  - name: tasks-conversion-webhook-server
    secret:
      secretName: tasks-conversion-webhook-server
      items:
      - key: crt
        path: server.crt
      - key: key
        path: server.key
---
apiVersion: v1
kind: Secret
metadata:
  name: tasks-conversion-webhook-server
data:
  crt: "SERVER_CRT"
  key: "SERVER_KEY"
---
apiVersion: v1
kind: Service
metadata:
  name: tasks-conversion-webhook-server
spec:
  selector:
    app.kubernetes.io/name: tasks-conversion-webhook-server
  ports:
  - protocol: TCP
    port: 9443
    targetPort: 9443
